server:
  port: 8080
  servlet:
    #    context-path: /backend
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  upload-dir: ./uploads

thresholdValue: 5


spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/yemektarifiodev?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


logging:
  level:
    org.springframework.web: debug